#+TITLE: Introduction to Geospatial Data Analysis with Python

A sequence of four workshops for the [[https://gradquant.ucr.edu/][Graduate Quantitative Methods Center]] (aka
GradQuant) at the University of California, Riverside ([[http://ucr.edu][UCR]]), presented by [[http://spatial.ucr.edu/peopleRey.html][Dr.
Sergio Rey]], Founding Director of the [[http://spatial.ucr.edu/][UCR Center for Geospatial Sciences]].


This workshop series provides a gentle introduction to Python for geospatial
data analysis. Through hands-on instruction, the workhops cover the open source
Python Spatial Analysis Library ([[http://pysal.readthedocs.io/en/latest/index.html][PySAL]]) and the related Python ecosystem of
libraries to facilitate common tasks for scientists and researchers working
with geospatial data, and to provide an introduction to methods of exploratory
spatial data analysis and spatial econometrics.

* Workshops
The series is organized into four workshops that provide computationally based introductions
to the /processing/, /visualization/, /exploration/, and /modeling/ of geospatial data.

 (All workshops are from 9:10-11:00 a.m. on the dates listed.)
** Workshop 1 (April 24): Geospatial Data Processing with Python 
Geospatial data comes in a rich variety of formats and from many different
sources. Wrangling geospatial data is often a major component of any applied
research project, and becoming efficient in geoprocessing is thus vital. This first workshop
provides an overview of methods for dealing with the /processing/ of geospatial
data. This includes importing, and integrating, data in different formats (e.g.
shapefile, GeoJSON, WKT, WKB), and the treatment of different spatial coordinate
reference systems. Methods of deterministic spatial analysis involving
topological relationships and spatial operations including buffering,
dissolving, clipping, splitting and others, are covered.
*** Lesson Notebooks and pdfs
- Introduction to Shapely ([[https://github.com/sjsrey/gdapy18/blob/master/content/shapely.ipynb][Notebook]], [[https://github.com/sjsrey/gdapy18/blob/master/content/shapely.pdf][pdf]])
- Introduction to Geopandas ([[https://github.com/sjsrey/gdapy18/blob/master/content/geopandas_intro.ipynb][Notebook]], [[https://github.com/sjsrey/gdapy18/blob/master/content/geopandas_intro.pdf][pdf]])
- Geoprocessing with Geopandas ([[https://github.com/sjsrey/gdapy18/blob/master/content/geopandas_buffering.ipynb][Notebook]], [[https://github.com/sjsrey/gdapy18/blob/master/content/geopandas_buffering.pdf][pdf]])

** Workshop 2 (May 1): Geovisualization

The second workshop focuses on the /visualization/ of geospatial data. Here we
explore a number of Python libraries for scientific visualization in general,
and geovisualization in particular. Basic cartographic concepts involving
choropleth mapping, color schemes, and attribute classification are covered.
Methods for exploratory visualization where the focus is on quickly generating
graphical depictions and gather insights from geospatial are also examined. 
Libraries supporting publication quality visualizations are presented. Finally,
the development of interactive geovisualizations is introduced.

** Workshop 3 (May 15): Exploratory Spatial Data Analysis 
This workshop provides and introduction to methods that support the
/exploration/ of spatial data. The goal of these methods is to uncover and
detect interesting geographical patterns. The formal representation of neighbor
relationships via spatial weights matrices are discussed. Global tests for spatial
autocorrelation are covered, followed by local autocorrelation methods designed
to detect hot-spots in geospatial data patterns. Methods for the exploration of
spatial-temporal data are also introduced.


** Workshop 4 (May 22): Introduction to Spatial Econometrics
The final workshop in this series provides an introduction to the /modeling/ of
relationships in spatial data using methods of [[https://www.amazon.com/Modern-Spatial-Econometrics-Practice-GeoDaSpace/dp/0986342106][modern spatial econometrics]]. The
complications that arise due to spatial dependence and spatial
heterogeneity in empirical data sets are explored. Methodological topics include an
overview of model specifications for regression with spatial data, methods of
estimation, model diagnostics, and validation issues. 
